version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - checkout

      - run:
          name: "Install Hugo"
          command: curl -sL -o/tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.61.0/hugo_0.61.0_Linux-64bit.deb && sudo dpkg -i /tmp/hugo.deb

      - run:
          name: "Install dependencies"
          command: yarn

      - run:
          name: "Build project"
          command: yarn run build

      - persist_to_workspace:
          root: ~/hugo/
          paths:
            - public

  deploy:
    docker:
      - image: olizilla/ipfs-dns-deploy:latest
        environment:
          DOMAIN: research.protocol.ai
          BUILD_DIR: public
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy website to IPFS
          command: |
            pin_name="$DOMAIN build $CIRCLE_BUILD_NUMBER"

            hash=$(pin-to-cluster.sh "$pin_name" /tmp/workspace/$BUILD_DIR)

            echo "Website added to IPFS: https://ipfs.io/ipfs/$hash"

            echo "https://ipfs.io/ipfs/$hash" > build_url.txt

            if [ "$CIRCLE_BRANCH" == "master" ] ; then
              dnslink-dnsimple -d $DOMAIN -r _dnslink -l /ipfs/$hash
            fi
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - build_url.txt

    lighthouse-audits:
      docker:
        - image: kporras07/lighthouse-ci
      steps:
        - attach_workspace:
            at: /tmp/workspace
        - run:
            name: Run lighthouse against deployment
            command: |
              TEST_URL=$(<build_url.txt)

              lighthouse $TEST_URL \
                --port=9222 \
                --chrome-flags=\"--headless\" \
                --output-path=/home/chrome/reports/anonymous-"$(echo -n $CIRCLE_SHELL_ENV | md5sum | awk '{print $1}')" \
                --output=json \
                --output=html

        - persist_to_workspace:
            root: /home/chrome
            paths:
              - reports
    processResults:
      docker:
        - image: circleci/node:10.15.0
      steps:
        - checkout
        - attach_workspace:
          at: /tmp/workspace
        - run:
            name: "Install dependencies"
            command: yarn
        - store_artifacts:
            path: reports
            destination: reports
        - run:
            name: Analyze and report desired vs actual lighthouse scores
            command: ./circleci/analyze_lighthouse_scores.js package.json reports

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          context: ipfs-dns-deploy
          requires:
            - build
      - lighthouse-audits:
          requires:
            - deploy
